features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 0
logo:
  use_default: 0
  path: themes/custom/badcamp2017/images/badcamp2017-logo.png
favicon:
  use_default: 1
