theme: current
defaults:
  sender: sendgrid_integration
  formatter: swiftmailer
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: swiftmailer
      sender: sendgrid_integration
  sendgrid_integration:
    none:
      formatter: sendgrid_integration
      sender: sendgrid_integration
