site_key: 6LfJXSoUAAAAAGDvBYWQLJsG2S01rE61WKAyYm_Y
secret_key: 6LfJXSoUAAAAALIiBebMsZbaNGI3fnOG1mxo1-0P
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
