#!/bin/bash

# Go to base level of project
cd "$(dirname $0)/../../"

# Exit immediately on errors, and echo commands as they are executed.
set -ex

# Set the $PATH to include the global composer bin directory.
PATH=$PATH:~/.composer/vendor/bin

fin refresh

KEY=$(cat ~/.ssh/id_rsa.pub); fin exec "echo \"${KEY}\" > ~/.ssh/authorized_keys"

export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://badcamp2017.docksal/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "alias":  "@docksal.badcamp2017" }}}}'
cd tests && ../vendor/bin/behat --config=behat-pantheon.yml "$@"
